export default function TermsPage() {
  return (
    <main className="min-h-screen bg-black text-white px-6 py-10 flex justify-center">
      <div className="max-w-3xl w-full">
        <h1 className="text-3xl font-bold mb-6">Terms of Service</h1>

        <p className="text-sm text-zinc-300 mb-4">
          Last updated: March 2026
        </p>

        <p className="text-sm text-zinc-300 mb-6">
          These Terms govern your use of FunGen (“we”, “our”, “us”) and our AI‑powered services at fungen.com.au.
        </p>

        <h2 className="text-xl font-semibold mt-8 mb-3">Use of Service</h2>

        <p className="text-sm text-zinc-300 mb-6">
          FunGen provides AI‑generated roast content for entertainment purposes only. You agree not to misuse the service or generate harmful, abusive, or illegal content.
        </p>

        <h2 className="text-xl font-semibold mt-8 mb-3">Subscriptions</h2>

        <ul className="text-sm text-zinc-300 space-y-2 mb-6">
          <li>• Savage Mode is billed weekly via Stripe.</li>
          <li>• Subscriptions renew automatically until canceled.</li>
          <li>• You can manage or cancel your subscription via the Billing Portal.</li>
          <li>• Clearing cookies may require using Restore Purchase.</li>
        </ul>

        <h2 className="text-xl font-semibold mt-8 mb-3">Refunds</h2>

        <p className="text-sm text-zinc-300 mb-6">
          Refunds are handled directly through Stripe. We do not issue manual refunds unless required by law.
        </p>

        <h2 className="text-xl font-semibold mt-8 mb-3">AI Content</h2>

        <p className="text-sm text-zinc-300 mb-6">
          AI outputs may be unpredictable. You agree that FunGen is not responsible for any content generated by the AI.
        </p>

        <h2 className="text-xl font-semibold mt-8 mb-3">Limitation of Liability</h2>

        <p className="text-sm text-zinc-300 mb-6">
          FunGen is provided “as is” without warranties. We are not liable for damages arising from use of the service.
        </p>

        <h2 className="text-xl font-semibold mt-8 mb-3">Changes to Terms</h2>

        <p className="text-sm text-zinc-300 mb-6">
          We may update these Terms at any time. Continued use of the service means you accept the updated Terms.
        </p>

        <h2 className="text-xl font-semibold mt-8 mb-3">Contact</h2>

        <p className="text-sm text-zinc-300 mb-6">
          Email: support@fungen.com.au
        </p>
      </div>
    </main>
  );
}
